<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CYBERSPACE" name="com.zaigo.reactui.EditCompanyTestCases" tests="17" failures="1" timestamp="2021-05-20T22:43:44 IST" time="14.297" errors="0">
  <testcase name="verifyUserTab" time="6.116" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyCompanyTab" time="0.165" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="modalPopup" time="1.233" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyEmptyName" time="0.220" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyMaxName" time="0.484" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyEmptySpacesinOwner" time="0.217" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyMaxOwnerName" time="0.300" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyLocationOne" time="1.560" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyEmailFormat" time="0.189" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyPhoneFormat" time="0.207" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyMaxContactPerson" time="0.276" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyMaxLineOne" time="0.444" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyMaxCity" time="0.399" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyMaxLineTwo" time="0.396" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyMaxZip" time="0.469" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
  <testcase name="verifyUpdatedSuccessfully" time="1.540" classname="com.zaigo.reactui.EditCompanyTestCases">
    <failure type="java.lang.AssertionError" message="expected [Updated Successfully] but found [Edited Successfully]">
      <![CDATA[java.lang.AssertionError: expected [Updated Successfully] but found [Edited Successfully]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.zaigo.reactui.EditCompanyTestCases.verifyUpdatedSuccessfully(EditCompanyTestCases.java:530)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyUpdatedSuccessfully -->
  <system-out/>
  <testcase name="verifyNameUpdated" time="0.082" classname="com.zaigo.reactui.EditCompanyTestCases"/>
  <system-out/>
</testsuite> <!-- com.zaigo.reactui.EditCompanyTestCases -->
